### ISSUE TITLE
Allow localization of snapcraft.io

### ISSUE THREAD

**Issue by Winael** [canonical-webteam-archive/snapcraft.io-static-pages#13]
To promote snapcraft.io more, it would be great to allow localization. Users could read the information in their native languages, so we can reach more people.

For now the portal is only accessible for English-speaking people.

I begin to work on a translation of the portal into french. As soon it is ready I could pull request it.

**Comment by anthonydillon** [comment]
@Winael Thank you very much. Internalisation is a highly desired feature for the site and we would love to support it. I will ask our translation team what would be the best way forward.

**Comment by anthonydillon** [comment]
@Winael I have created a launchpad project to translate the site into as many languages as possible. If you could please help translate to French there. That would be best as it will be kept up to date with site changes.
https://translations.launchpad.net/snapcraft.io

**Comment by Winael** [comment]
Hi Anthony,

It seems that strings wasn't well extracted. It seems to due to simple
quote characters inside strings. Some strings are very hard to translate

**Comment by matthewpaulthomas** [comment]
I see four main things to fix, in order:
1. As @Winael suggested, the strings are being split on apostrophes, and also inappropriately on inline markup. This results in strings such as “[s just what](https://translations.launchpad.net/snapcraft.io/trunk/+pots/snapcraft.io/pt_BR/18/+translate)” and “[we have a fun crowd of people who hang out on the](https://translations.launchpad.net/snapcraft.io/trunk/+pots/snapcraft.io/pt_BR/70/+translate)”. Even if these scraps were translated, the combined result would be garble.
1. The strings are not being regenerated when the code changes. For example, in #340 I changed the front page to say “[the easiest way to build a snap is with our auto-build service … Otherwise, you can use Snapcraft…](https://github.com/canonical-websites/snapcraft.io/pull/340/files)”. But the translation template still says “[the easiest way to build a snap is with snapcraft](https://translations.launchpad.net/snapcraft.io/trunk/+pots/snapcraft.io/pt_BR/85/+translate)”.
1. The various CMSes need to generate and serve the localized versions to a defined URL schema (for example, `?lang=`_languagecode_).
1. There needs to be a language switcher to get to those localized versions, in a consistent place on the snapcraft.io page layout. (Maybe this could be accompanied by a link for people to help out with the localization.)

**Comment by nottrobin** [comment]
This issue was moved to canonical-websites/snapcraft.io#131
