### ISSUE TITLE
snapcraft docs should be searchable

### ISSUE THREAD

**Issue by jamiedbennett** [canonical-webteam-archive/snapcraft.io-static-pages#238]
## Summary

The snapcraft.io website should be searchable. A quick hack could be to use search-via-google.

**Comment by magdalena-mirowicz** [comment]
Thanks for raising this. I added this to our backlog of work

**Comment by campbieil** [comment]
Why make the site searchable? Isn't making the documentation searchable sufficient? I do not believe the other pages have anything major that needs searching. Am I missing something?

**Comment by luzfcb** [comment]
about snapcraft documentation only:

The problem I had was: 

I needed to know how to use the `SNAPCRAFT_STAGE` variable

Currently, there is no way to search for all the occurrences of `SNAPCRAFT_STAGE` on documentation.

A possible solution: The snapcraft documentation is created in Markdown ( https://github.com/snapcore/snapcraft/tree/master/docs )

As snapcraft is an almost 100% Python project, I would suggest use the sphinx-doc + http://www.sphinx-doc.org/en/stable/markdown.html to solve this problem,  because, sphinx-doc already implements the search, and many other useful functionalities for software documentation, and supports themes, and it is very extensible.

http://www.sphinx-doc.org/en/stable/theming.html

**Comment by nottrobin** [comment]
This issue was moved to canonical-docs/snappy-docs#173
